# Generated by Django 4.2.4 on 2023-08-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cielo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover_img', models.CharField(max_length=150)),
                ('subtitle', models.TextField()),
                ('video', models.CharField(max_length=50)),
                ('video_text', models.TextField()),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('img1', models.CharField(max_length=150)),
                ('img1_text', models.TextField()),
            ],
        ),
    ]
