# Generated by Django 4.2.4 on 2023-08-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cielo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cielo',
            name='video2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
