# Generated by Django 4.2.4 on 2023-08-06 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_alquimia_img1_text_alter_alquimia_img2_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquimia',
            name='list1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), size=None),
        ),
        migrations.AlterField(
            model_name='alquimia',
            name='list2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), size=None),
        ),
        migrations.AlterField(
            model_name='cartografia',
            name='list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), size=None),
        ),
        migrations.AlterField(
            model_name='gestarpariralumbrar',
            name='list1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), size=None),
        ),
        migrations.AlterField(
            model_name='gestarpariralumbrar',
            name='list2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), size=None),
        ),
        migrations.AlterField(
            model_name='gestarpariralumbrar',
            name='list3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), size=None),
        ),
        migrations.AlterField(
            model_name='gestarpariralumbrar',
            name='list4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), size=None),
        ),
        migrations.AlterField(
            model_name='gestarpariralumbrar',
            name='list5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), size=None),
        ),
        migrations.AlterField(
            model_name='tejedora',
            name='list1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), size=None),
        ),
        migrations.AlterField(
            model_name='tejedora',
            name='list2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), size=None),
        ),
    ]
