# Generated by Django 4.2.4 on 2023-08-24 23:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_alquimia_list1_alter_alquimia_list2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquimia',
            name='list1bis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alquimia',
            name='list2bis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cartografia',
            name='listbis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gestarpariralumbrar',
            name='list1bis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gestarpariralumbrar',
            name='list2bis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gestarpariralumbrar',
            name='list3bis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gestarpariralumbrar',
            name='list4bis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gestarpariralumbrar',
            name='list5bis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tejedora',
            name='list1bis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tejedora',
            name='list2bis',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='alquimia',
            name='list1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='alquimia',
            name='list2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='cartografia',
            name='list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gestarpariralumbrar',
            name='list1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gestarpariralumbrar',
            name='list2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gestarpariralumbrar',
            name='list3',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gestarpariralumbrar',
            name='list4',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gestarpariralumbrar',
            name='list5',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='tejedora',
            name='list1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='tejedora',
            name='list2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=550), null=True, size=None),
        ),
    ]
