# Generated by Django 4.2.4 on 2023-09-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=400)),
                ('img', models.CharField(max_length=400)),
                ('text', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
