# Generated by Django 4.2.4 on 2023-08-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.CharField(max_length=150)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('quote', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
    ]
